# =============================================================================
# Discipline OS — developer Makefile
# See CLAUDE.md §Dev environment for full command reference.
# =============================================================================

.PHONY: up down logs reset \
        api-shell db-shell redis-shell \
        migrate migrate-new migrate-down \
        test-api test-web test \
        lint typecheck \
        localstack-init

# -----------------------------------------------------------------------------
# Docker Compose stack
# -----------------------------------------------------------------------------

## Start all local services (postgres, redis, localstack, mailhog) in the background
up:
	docker compose up -d
	@echo ""
	@echo "  Stack is up."
	@echo "    Postgres  : localhost:5432  (discipline / devpassword / discipline_dev)"
	@echo "    Redis     : localhost:6379"
	@echo "    LocalStack: http://localhost:4566"
	@echo "    Mailhog   : http://localhost:8025"

## Stop containers (volumes preserved)
down:
	docker compose down

## Tail logs from all services
logs:
	docker compose logs -f

## Wipe and restart — destroys all local DB data (destructive!)
reset:
	docker compose down -v
	docker compose up -d
	@echo "Stack reset. Run 'make migrate' to re-apply migrations."

# -----------------------------------------------------------------------------
# Shells
# -----------------------------------------------------------------------------

## Open a psql shell inside the postgres container
db-shell:
	docker compose exec postgres psql -U discipline -d discipline_dev

## Open a redis-cli shell inside the redis container
redis-shell:
	docker compose exec redis redis-cli

## Start the FastAPI dev server (hot-reload on port 8000)
api-shell:
	cd services/api && uv run uvicorn discipline.app:app --reload --host 0.0.0.0 --port 8000

# -----------------------------------------------------------------------------
# Database migrations (Alembic)
# -----------------------------------------------------------------------------

## Apply all pending migrations
migrate:
	cd services/api && uv run alembic upgrade head

## Roll back one migration step
migrate-down:
	cd services/api && uv run alembic downgrade -1

## Create a new autogenerated migration  (usage: make migrate-new name="add_foo_table")
migrate-new:
	@if [ -z "$(name)" ]; then echo "Usage: make migrate-new name=\"description\""; exit 1; fi
	cd services/api && uv run alembic revision --autogenerate -m "$(name)"

# -----------------------------------------------------------------------------
# LocalStack bootstrap
# Creates the S3 buckets and SQS queues expected by the API.
# Re-runnable; safe to call after 'make reset'.
# -----------------------------------------------------------------------------
localstack-init:
	@echo "Bootstrapping LocalStack resources..."
	AWS_ACCESS_KEY_ID=test AWS_SECRET_ACCESS_KEY=test AWS_DEFAULT_REGION=us-east-1 \
	  aws --endpoint-url=http://localhost:4566 s3 mb s3://discipline-voice-blobs --region us-east-1 2>/dev/null || true
	AWS_ACCESS_KEY_ID=test AWS_SECRET_ACCESS_KEY=test AWS_DEFAULT_REGION=us-east-1 \
	  aws --endpoint-url=http://localhost:4566 s3 mb s3://discipline-exports --region us-east-1 2>/dev/null || true
	AWS_ACCESS_KEY_ID=test AWS_SECRET_ACCESS_KEY=test AWS_DEFAULT_REGION=us-east-1 \
	  aws --endpoint-url=http://localhost:4566 s3 mb s3://discipline-assets --region us-east-1 2>/dev/null || true
	AWS_ACCESS_KEY_ID=test AWS_SECRET_ACCESS_KEY=test AWS_DEFAULT_REGION=us-east-1 \
	  aws --endpoint-url=http://localhost:4566 sqs create-queue --queue-name discipline-general 2>/dev/null || true
	AWS_ACCESS_KEY_ID=test AWS_SECRET_ACCESS_KEY=test AWS_DEFAULT_REGION=us-east-1 \
	  aws --endpoint-url=http://localhost:4566 sqs create-queue --queue-name discipline-voice 2>/dev/null || true
	AWS_ACCESS_KEY_ID=test AWS_SECRET_ACCESS_KEY=test AWS_DEFAULT_REGION=us-east-1 \
	  aws --endpoint-url=http://localhost:4566 sqs create-queue --queue-name discipline-embed 2>/dev/null || true
	@echo "LocalStack bootstrap complete."

# -----------------------------------------------------------------------------
# Tests
# -----------------------------------------------------------------------------

## Run FastAPI / Python unit tests
test-api:
	cd services/api && uv run pytest -q

## Run all web/package unit tests (Vitest)
test-web:
	pnpm test

## Run all tests (API + web)
test: test-api test-web

# -----------------------------------------------------------------------------
# Lint / typecheck
# -----------------------------------------------------------------------------

## Lint everything (ruff + eslint)
lint:
	cd services/api && uv run ruff check .
	pnpm run lint

## Typecheck everything (mypy + tsc)
typecheck:
	cd services/api && uv run mypy .
	pnpm run typecheck

# -----------------------------------------------------------------------------
# Web surfaces (individual dev servers)
# -----------------------------------------------------------------------------

## Marketing site  — http://localhost:3010
web-marketing:
	pnpm --filter @disciplineos/web-marketing dev

## Consumer app    — http://localhost:3020
web-app:
	pnpm --filter @disciplineos/web-app dev

## Clinician portal — http://localhost:3030
web-clinician:
	pnpm --filter @disciplineos/web-clinician dev

## Enterprise admin — http://localhost:3040
web-enterprise:
	pnpm --filter @disciplineos/web-enterprise dev

## Crisis surface (static export build + serve) — http://localhost:3050
web-crisis:
	pnpm --filter @disciplineos/web-crisis build
	pnpm --filter @disciplineos/web-crisis start
