"""Request ID middleware.

Every inbound request is assigned a unique identifier that threads through all
log lines emitted while handling that request.  The ID is propagated as
``X-Request-ID`` on the response so clients can correlate their own traces with
the backend log entries.

ID source priority
------------------
1. ``X-Request-ID`` header supplied by the client (e.g. a web-app that generates
   its own trace IDs).  Accepted only when it is ≤ 64 characters and contains
   only ASCII alphanumeric characters or hyphens.  Any header that fails
   validation is silently replaced with a server-generated UUID.
2. A fresh ``uuid4`` generated by this middleware when the client provides no
   header (or an invalid one).

The ID is stored in a :class:`contextvars.ContextVar` so log formatters can
call :func:`get_request_id` from anywhere in the call stack without having to
thread the ``Request`` object through every helper.

Structlog integration
---------------------
:func:`get_request_id` is intentionally a plain function rather than a structlog
processor so that non-structlog code (e.g. SQLAlchemy event handlers, background
tasks that inherit the context) can retrieve the ID without depending on the
logging stack.  Structlog processors should call ``get_request_id()`` and bind
the result to the log context via ``structlog.contextvars.bind_contextvars``.
"""

from __future__ import annotations

import re
import uuid
from collections.abc import Awaitable, Callable
from contextvars import ContextVar

from fastapi import Request
from starlette.middleware.base import BaseHTTPMiddleware
from starlette.responses import Response
from starlette.types import ASGIApp

_REQUEST_ID_HEADER: str = "X-Request-ID"
_MAX_ID_LENGTH: int = 64
# Only alphanumeric chars and hyphens are accepted from the client to prevent
# header-injection attacks and keep IDs safe for structured log fields.
_VALID_ID_RE: re.Pattern[str] = re.compile(r"^[a-zA-Z0-9\-]+$")

# Module-level ContextVar — one value per async task (i.e. per request).
_request_id_var: ContextVar[str] = ContextVar("request_id", default="")


def get_request_id() -> str:
    """Return the request ID for the current async context.

    Returns an empty string when called outside a request context (e.g. in
    startup hooks or worker tasks that have not set a request ID).
    """
    return _request_id_var.get()


def _parse_or_generate(header_value: str | None) -> str:
    """Validate *header_value* and return it, or generate a fresh UUID.

    Validation rules (both must pass):
    - Length ≤ 64 characters.
    - Matches ``^[a-zA-Z0-9\\-]+$`` (alphanumeric + hyphens only).
    """
    if header_value and len(header_value) <= _MAX_ID_LENGTH and _VALID_ID_RE.match(header_value):
        return header_value
    return str(uuid.uuid4())


class RequestIdMiddleware(BaseHTTPMiddleware):
    """Assign a request ID to every inbound request.

    Registration::

        app.add_middleware(RequestIdMiddleware)

    After registration, :func:`get_request_id` returns the ID from anywhere in
    the async call stack for the duration of that request.
    """

    def __init__(self, app: ASGIApp) -> None:
        super().__init__(app)

    async def dispatch(
        self,
        request: Request,
        call_next: Callable[[Request], Awaitable[Response]],
    ) -> Response:
        request_id = _parse_or_generate(request.headers.get(_REQUEST_ID_HEADER))

        # Bind into the async context so log lines emitted downstream carry
        # the ID without any explicit argument threading.
        token = _request_id_var.set(request_id)
        try:
            response = await call_next(request)
        finally:
            # Restore the previous context value so the ContextVar does not
            # leak across recycled event-loop tasks in test environments.
            _request_id_var.reset(token)

        response.headers[_REQUEST_ID_HEADER] = request_id
        return response


__all__ = [
    "RequestIdMiddleware",
    "get_request_id",
]
